Repository arfc/cairo, pull requests merged in 2020-12, with the labels that each got.

#55 Surface Plotting
  cosine_example.ipynb
  optimizers.py
  requirements.txt
Labels: Comp:Build, Difficulty:1-Beginner, Priority:1-Critical, Status:5-In Review, Type:feature

#56 Sunrise Examples and Sphinx Documentation
  .gitignore
  README.md
  docs/Makefile
  docs/conf.py
  docs/examples/examples.rst
  docs/examples/examples_lorenz.rst
  docs/examples/examples_sunrise.rst
  docs/examples/examples_tools.rst
  docs/examples/plots/sunrise_plots/.DS_Store
  docs/examples/plots/sunrise_plots/dec_1year.png
  docs/examples/plots/sunrise_plots/et_2year.png
  docs/examples/plots/sunrise_plots/ha_4day.png
  docs/examples/plots/sunrise_plots/lst_4day.png
  docs/examples/plots/sunrise_plots/lt_2day.png
  docs/examples/plots/sunrise_plots/se_ov_dec.png
  docs/examples/plots/sunrise_plots/se_zin.png
  docs/examples/plots/sunrise_plots/tc_2year.png
  docs/examples/plots/sunrise_plots/yf_1year.png
  docs/index.rst
  docs/make.bat
  docs/modules.rst
  docs/sunrise.rst
  docs/tests.rst
  docs/tools.rst
  requirements.txt
  solar_elevation_demand.csv
  sunrise.py
  tests/test_lorenz.py
  tests/test_sunrise.py
  tools.py
Labels: Type:documentation

#57 Adds Snakemake and Driver
  .gitignore
  Snakefile
  cosine_example.ipynb
  data/railsplitter_data.csv
  data/solarfarm_data.csv
  driver.py
  lorenz.py
  lorenz_driver.py
  loss_plots.py
  optimizers.py
  requirements.txt
  sunrise.py
  tools.py
Labels: Comp:Analysis, Difficulty:2-Challenging, Priority:1-Critical, Status:5-In Review, Type:enhancement
